# Generated by Django 4.2.3 on 2023-07-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
    ]
