# Generated by Django 4.2.3 on 2023-07-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_participant_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='participant_count',
        ),
    ]
