# Generated by Django 4.2.3 on 2023-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
